package org.educa.service;

import generated.Producto;
import generated.Productos;
import jakarta.xml.bind.JAXBException;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.*;
import org.educa.dao.ProductoDAO;
import org.educa.dao.ProductoDAOImpl;
import org.educa.entity.ProductoEntity;
import org.educa.entity.SummaryEntity;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.text.ParseException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

public class ProductoService {

    // DataBase of the first exercise
    private final ProductoDAO productoDAO = new ProductoDAOImpl();


    /**
     * First method is about the first exercise, reading the xml File and return a list with the products and specific methods calculations.
     *
     * @param fileXml This is about the conversion to convert the xml to a File to read it from Java.
     * @return the variable "resultado" that is a list of "productoEntity" with the final price, cost and benefits.
     * @throws JAXBException it's like an IOException doing a try catch on the main.
     */
    public List<ProductoEntity> readFile(String fileXml) throws JAXBException {

        Productos productoData = productoDAO.readXml(fileXml);
        List<ProductoEntity> resultado = new ArrayList<>();
        for (Producto producto : productoData.getProducto()) {
            resultado.add(createProductoEntity(producto));
        }
        return resultado;
    }

    /**
     * Read a product XML then calculates the total profit and exports a summary file
     *
     * @param path    this is the destination directory path where the file will be saved
     * @param fileXml this is the absolute path of the XML file
     * @throws JAXBException control if occur an error of unmarshalling or reading the XML file
     * @throws IOException   if an error occcurs while creating or writing the summary
     */

    public void exportSummary(String path, String fileXml) throws JAXBException, IOException {
        // Read the list of products and then calculate the total profit
        List<ProductoEntity> productoEntities = readFile(fileXml);
        BigDecimal beneficioTotal = calculateTotalBenefit(productoEntities);

        // Prepare the file and destination
        File file = buildNameTxt(path, fileXml);

        // Create the summary entity
        SummaryEntity summaryEntity = createSummaryEntity(productoEntities.size(), beneficioTotal, file);

        // This is the first write to generate the txt on the disk
        productoDAO.writeFile(summaryEntity);

        // Measures the file size
        summaryEntity.setFileSize(file.length());

        // This is de second write to save the final information with the correct lenght
        productoDAO.writeFile(summaryEntity);

    }

    /*
        We had a lot of problems when we tried programming horizontal because when we did the merge,
        we had a merge confliction,
        and we solve it thanks to the tools of GitHub pointing out the problems of the code.
     */

    /**
     * This method is about of exporting the excel from the xml file with the help of the library of apache poi.
     *
     * @param path    destination of directory path.
     * @param fileXml the input XML path.
     * @throws JAXBException  is de main exception for all the errors concurring while the proccess xml link.
     * @throws IOException    this eror is for the operations of input and output.
     * @throws ParseException for the wrong string text.
     */
    public void exportExcel(String path, String fileXml) throws JAXBException, IOException, ParseException {
        // This recibe the products using methods of exercise 1
        List<ProductoEntity> productos = readFile(fileXml);
        // We create the book and file of Excel
        XSSFWorkbook libro = new XSSFWorkbook();
        XSSFSheet hoja = libro.createSheet("ResumenInventario");

        // Calling teh auxiliar methods
        createHeaderRow(hoja);
        fillDataRows(hoja, productos);

        // We generate the dynamic file name requested in the instructions
        String timestamp = String.valueOf(System.currentTimeMillis());
        String fileName = "export_" + timestamp + ".xlsx";

        saveExcelFile(libro, path, fileName);
    }

    /**
     * Takes a generated JAXB Producto, creates a new ProductoEntity, and calculates its financial fields.
     *
     * @param producto the raw product object generated by JAXB from the XML file.
     * @return a complete ProductoEntity containing the raw data and the calculated financial results.
     */
    private ProductoEntity createProductoEntity(Producto producto) {
        ProductoEntity entity = new ProductoEntity();
        entity.setProducto(producto);

        BigDecimal precioFinal = calculateFinalPrice(producto.getPrecio(), producto.getDescuento());
        entity.setPrecioFinal(precioFinal);

        BigDecimal costes = calculateTotalCost(producto.getCostes().getCostesAlmacenaje(), producto.getCostes().getCostesEnvio());
        entity.setCost(costes);

        BigDecimal beneficio = calculateProfit(precioFinal, costes);
        entity.setProfit(beneficio);

        return entity;
    }


    /**
     * Calculates the final price with the percentual discount and doing a value.of.
     *
     * @param originalPrice      the initial price of the product without discount.
     * @param discountPercentage the discount to apply as a percentage.
     * @return the final price after subtracting the calculated discount.
     */
    private BigDecimal calculateFinalPrice(BigDecimal originalPrice, BigDecimal discountPercentage) {
        /*
            We had to investigate about the BigDecimal because we thought that is a primal type,
            we tried to do it like with basics maths but it didn't work,
            finally we discovered about this is am object and we have to use the specific methods.
        */
        BigDecimal discountValue = originalPrice.multiply(discountPercentage).divide(BigDecimal.valueOf(100));
        return originalPrice.subtract(discountValue);
    }

    /**
     * Calculates the total cost by summing storage and shipping costs.
     *
     * @param almacenaje the cost to store the product in the warehouse.
     * @param envio      the cost to ship the product to the destination.
     * @return the sum of both storage and shipping costs.
     */
    private BigDecimal calculateTotalCost(BigDecimal almacenaje, BigDecimal envio) {
        return almacenaje.add(envio);
    }

    /**
     * Calculates the profit by subtracting total costs from the final price.
     *
     * @param finalPrice the price of the product after applying the discount.
     * @param totalCost  the sum of all costs (storage and shipping).
     * @return the profit of the product.
     */
    private BigDecimal calculateProfit(BigDecimal finalPrice, BigDecimal totalCost) {
        return finalPrice.subtract(totalCost);
    }


    /**
     * Sums the individual profit of all the products of the list.
     *
     * @param productoEntities list of product entities that contain the profit values.
     * @return the accumulated total profit.
     */

    private BigDecimal calculateTotalBenefit(List<ProductoEntity> productoEntities) {
        BigDecimal beneficioTot = BigDecimal.valueOf(0);
        for (ProductoEntity producto : productoEntities) {
            beneficioTot = beneficioTot.add(producto.getProfit());
        }
        return beneficioTot;
    }

    /**
     * Transform the input XML filename to a TXT summary format
     * and then create the directories if it doesn't exist.
     *
     * @param path    destination of directory path.
     * @param fileXml the input XML path.
     * @return an object with the directory and the new file name.
     */
    private File buildNameTxt(String path, String fileXml) {
        File xmlFile = new File(fileXml);
        String nombreXml = xmlFile.getName();

        String nombreTxt = nombreXml.replace("inventario_", "result_").replace(".xml", ".txt");

        File directorio = new File(path);
        if (!directorio.exists()) {
            directorio.mkdirs();
        }

        return new File(directorio, nombreTxt);
    }

    /**
     * Builds and filled the SummaryEntity with the product counts, total profit
     * and file paths.
     *
     * @param productosCuenta total number of processed products.
     * @param beneficioTotal  accumulate the profit sum.
     * @param finalFile       the output file reference.
     * @return a filled SummaryEntity with all the instances
     */
    private SummaryEntity createSummaryEntity(int productosCuenta, BigDecimal beneficioTotal, File finalFile) {
        SummaryEntity summary = new SummaryEntity();
        summary.setName(LocalDate.now().toString());
        summary.setNumberOfProducts(productosCuenta);
        summary.setTotalProfit(beneficioTotal);
        summary.setFileName(finalFile.getPath());
        summary.setFileAbsolutePath(finalFile.getAbsolutePath());
        return summary;
    }


    /**
     * Creates the first row of the Excel being the tittles of the columns.
     *
     * @param hoja is the Excel file.
     */
    private void createHeaderRow(XSSFSheet hoja) {
        XSSFWorkbook wb = hoja.getWorkbook();
        XSSFCellStyle headerStyle = wb.createCellStyle();

        // Setting up the font to bold
        XSSFFont font = wb.createFont();
        font.setBold(true);
        headerStyle.setFont(font);

        // Aligning the text to the center of the cell
        headerStyle.setAlignment(HorizontalAlignment.CENTER);
        headerStyle.setVerticalAlignment(VerticalAlignment.CENTER);
        // Applying the green borders using the auxiliar method
        applyGreenBorder(headerStyle);

        // Creating the first row, index 0
        XSSFRow filaCabecera = hoja.createRow(0);
        String[] titulos = {"Código", "Marca", "Modelo", "Categoría", "Precio Final", "Coste", "Beneficio"};

        // Iterating through the titles array to create and style each cell
        for (int i = 0; i < titulos.length; i++) {
            XSSFCell celda = filaCabecera.createCell(i);
            celda.setCellValue(titulos[i]);
            celda.setCellStyle(headerStyle);
        }
    }

    /**
     * This method fills the rows with new cells and putting the data.
     *
     * @param hoja      is the Excel file where the data will be added.
     * @param productos is a list of products entity with all the information.
     */
    private void fillDataRows(XSSFSheet hoja, List<ProductoEntity> productos) {
        XSSFWorkbook wb = hoja.getWorkbook();
        XSSFFont fontBold = wb.createFont();
        fontBold.setBold(true);

        // We create the styles, being 0 the white and 1 the green, all this in an array
        XSSFCellStyle[] estilos = {wb.createCellStyle(), wb.createCellStyle()};
        estilos[1].setFillForegroundColor(IndexedColors.LIGHT_GREEN.getIndex());
        estilos[1].setFillPattern(FillPatternType.SOLID_FOREGROUND);

        // Styles with the black text for the first column
        XSSFCellStyle[] estilosBold = {wb.createCellStyle(), wb.createCellStyle()};

        for (int i = 0; i < 2; i++) {
            estilos[i].setAlignment(HorizontalAlignment.CENTER);
            applyGreenBorder(estilos[i]);
            estilosBold[i].cloneStyleFrom(estilos[i]);
            estilosBold[i].setFont(fontBold);
        }

        int numFila = 1;
        for (ProductoEntity p : productos) {
            XSSFRow fila = hoja.createRow(numFila);
            // 1 is green for odd ones, 0 is white for even ones
            int colorIdx = (numFila % 2 != 0) ? 1 : 0;

            // We put the data in an array to avoid the creation of all the cells by hand
            Object[] datos = {
                    p.getProducto().getCodigo(), p.getProducto().getMarca(),
                    p.getProducto().getModelo(), p.getProducto().getCategoria(),
                    p.getPrecioFinal().doubleValue(), p.getCost().doubleValue(), p.getProfit().doubleValue()
            };

            for (int i = 0; i < datos.length; i++) {
                XSSFCell celda = fila.createCell(i);
                if (datos[i] instanceof String) celda.setCellValue((String) datos[i]);
                else celda.setCellValue((Double) datos[i]);

                celda.setCellStyle(i == 0 ? estilosBold[colorIdx] : estilos[colorIdx]);
            }
            numFila++;
        }

        for (int i = 0; i < 7; i++) hoja.autoSizeColumn(i);
    }

    /**
     * This method applies the green border on the table.
     * @param estilo this parameter is to set the style.
     */
    private void applyGreenBorder(XSSFCellStyle estilo) {
        // setting up the style from every border
        estilo.setBorderTop(BorderStyle.THIN);
        estilo.setTopBorderColor(IndexedColors.DARK_GREEN.getIndex());
        estilo.setBorderBottom(BorderStyle.THIN);
        estilo.setBottomBorderColor(IndexedColors.DARK_GREEN.getIndex());
        estilo.setBorderLeft(BorderStyle.THIN);
        estilo.setLeftBorderColor(IndexedColors.DARK_GREEN.getIndex());
        estilo.setBorderRight(BorderStyle.THIN);
        estilo.setRightBorderColor(IndexedColors.DARK_GREEN.getIndex());
    }

    /**
     * Do the validation and creates the directory if it doesn't exists and save it.
     *
     * @param libro is the Excel book with all the data.
     * @param path  is the destination directory.
     * @throws IOException this eror is for the operations of input and output.
     */
    private void saveExcelFile(XSSFWorkbook libro, String path, String fileName) throws IOException {
        File carpeta = new File(path);
        if (!carpeta.exists()){
            carpeta.mkdirs();
        }

        try (FileOutputStream salida = new FileOutputStream(new File(carpeta, fileName))) {
            libro.write(salida);
        }
        // try-with-resources close automatic the outputStream
        libro.close();
    }
}
